# Before running this script, the file "template_disturbance_years_manta.csv", generated by
# the script 01_create_disturbance_years.jl, should be renamed to "disturbance_years_manta.csv" and
# the columns `year_before` and `year_after` should be filled. Currently, this is done
# manually by eye picking from the Reef Monitoring Dashboard
# (https://apps.aims.gov.au/reef-monitoring/reefs)

distribution_manta_years_path = joinpath(DATA_DIR, "disturbance_years_manta.csv")
disturbance_manta_years = CSV.read(distribution_manta_years_path, DataFrame; stringtype=String, comment="#")
disturbance_manta_years.cover_before = zeros(Float64, nrow(disturbance_manta_years))
disturbance_manta_years.cover_after = zeros(Float64, nrow(disturbance_manta_years))

manta_tow_cache = CSV.read(
    joinpath(DATA_DIR, "manta_tow_raw_cache.csv"), DataFrame; stringtype=String, comment="#"
)

cache_mask = falses(nrow(disturbance_manta_years))
for reef_name in unique(disturbance_manta_years.reef_name)
    manta_cover = manta_tow_cache[manta_tow_cache.reef_name.==reef_name, [:report_year, :mean]]

    cache_mask .= disturbance_manta_years.reef_name .== reef_name
    reef_cyclones = disturbance_manta_years[cache_mask, :]

    # A reef with two disturbances in the same year would break the year-based mask below.
    @assert length(reef_cyclones.year) == length(unique(reef_cyclones.year))

    for cyclone in eachrow(reef_cyclones)
        year_before, year_after = cyclone.year_before, cyclone.year_after

        # Match on reef_name + year, not cyclone_name alone - COTS/"multiple" disturbances are
        # almost all named "unknown", so matching on name alone would let same-named
        # disturbances at a reef overwrite each other's cover.
        cache_mask .= disturbance_manta_years.reef_name .== reef_name
        cache_mask .= cache_mask .&& (disturbance_manta_years.year .== cyclone.year)

        try
            disturbance_manta_years[cache_mask, :cover_before] .= manta_cover[manta_cover.report_year.==year_before, :mean][1]
            disturbance_manta_years[cache_mask, :cover_after] .= manta_cover[manta_cover.report_year.==year_after, :mean][1]
        catch
            @info("Reef name: $reef_name \nCyclone: $cyclone")
            continue
        end
    end
end

split_cover!(disturbance_manta_years, "Rebe Reef", 2005, 2011, 2009)
split_cover!(disturbance_manta_years, "Martin Reef", 2013, 2017, 2015)

CSV.write(joinpath(DATA_DIR, "disturbance_cover_manta.csv"), disturbance_manta_years)
