# Before running this script, the file "template_disturbance_years_transect.csv", generated by
# the script 01_disturbance_years.jl, should be renamed to "disturbance_years_transect.csv" and
# the columns `year_before` and `year_after` should be filled. Currently, this is done
# manually by eye picking from the Reef Monitoring Dashboard
# (https://apps.aims.gov.au/reef-monitoring/reefs)

disturbance_years_transect_path = joinpath(DATA_DIR, "disturbance_years_transect.csv")
disturbance_years_transect = CSV.read(disturbance_years_transect_path, DataFrame; stringtype=String, comment="#")

_raw_composition = open_dataset(COMPOSITION_PATH).mean
composition_reef_ids = _raw_composition.location.val.data

# coral_composition.nc predates a taxa-naming fix upstream in ReefMonitoring.jl - relabel to
# this pipeline's functional_groups spelling (data itself is unchanged).
coral_composition = YAXArray(
    (
        Dim{:timesteps}(collect(_raw_composition.timesteps.val.data)),
        Dim{:taxa}(replace(
            collect(_raw_composition.taxa.val.data),
            "Corymboses_non_Acropora" => "Corymbose_non_Acropora"
        )),
        Dim{:location}(collect(_raw_composition.location.val.data)),
    ),
    _raw_composition.data,
    _raw_composition.properties
)

for group in functional_groups
    disturbance_years_transect[!, "cover_before_$(group)"] .= 0.0
    disturbance_years_transect[!, "cover_after_$(group)"] .= 0.0
end

transect_reefs = unique(disturbance_years_transect[:, [:reef_name, :reef_id]])
transect_reef_names = transect_reefs.reef_name
transect_reef_ids = string.(transect_reefs.reef_id)

cache_mask = falses(nrow(disturbance_years_transect))
for (reef_idx, reef_name) in enumerate(transect_reef_names)
    reef_id = transect_reef_ids[reef_idx]
    if !(reef_id in composition_reef_ids)
        @info("Reef ID not found in coral_composition: $reef_id")
        continue
    end

    target_cover = coral_composition[location=At(reef_id), taxa=At(functional_groups)]

    cache_mask .= disturbance_years_transect.reef_name .== reef_name
    reef_disturbances = disturbance_years_transect[cache_mask, :]

    @assert length(reef_disturbances.year) == length(unique(reef_disturbances.year))

    for disturbance in eachrow(reef_disturbances)
        year_before, year_after = disturbance.year_before, disturbance.year_after

        cache_mask .= disturbance_years_transect.reef_name .== reef_name
        cache_mask .= cache_mask .&& (disturbance_years_transect.year .== disturbance.year)

        try
            cover_before = read(target_cover[timesteps=At(year_before)])
            cover_after = read(target_cover[timesteps=At(year_after)])
            disturbance_years_transect[cache_mask, cover_before_col_names] .= cover_before'
            disturbance_years_transect[cache_mask, cover_after_col_names] .= cover_after'
        catch e
            @info "Reef name: $reef_name \nDisturbance: $disturbance" exception = e
            continue
        end
    end
end

@assert all(Matrix(.!isnan.(disturbance_years_transect[!, cover_before_col_names])))
@assert all(Matrix(.!isnan.(disturbance_years_transect[!, cover_after_col_names])))
@assert all((0.0 .<= Matrix(disturbance_years_transect[!, cover_before_col_names]) .<= 1.0))
@assert all((0.0 .<= Matrix(disturbance_years_transect[!, cover_after_col_names]) .<= 1.0))

split_taxa_cover!(disturbance_years_transect, "Taylor Reef", 2016, 2018)
split_taxa_cover!(disturbance_years_transect, "Hoskyn Island", 2008, 2010)

zero_before_mask = sum(Matrix(disturbance_years_transect[!, cover_before_col_names]), dims=2) .== 0.0
zero_after_mask = sum(Matrix(disturbance_years_transect[!, cover_after_col_names]), dims=2) .== 0.0
deleteat!(disturbance_years_transect, getindex.(findall(zero_before_mask .&& zero_after_mask), 1))

CSV.write(joinpath(DATA_DIR, "disturbance_cover_transect.csv"), disturbance_years_transect)
