"""
Setup the parameter bounds and ordering for calibration.

Define standard global variables for which this ordering and naming can be accessed.
"""

import Base: copy

"""
    scale_factor_vec_to_array(sf_vec::AbstractVector{T}, n_taxa::Int64, n_biogroups::Int64, n_p_types::Int64)::Array{T, 3} where T <: Union{Float64, String, Tuple}
 
Reshape a scale factor vector to be an array of dimensions [taxa ⋅ param_type ⋅ biogroups].
Wrapper of reshape(vec, (n_taxa, n_p_types, n_biogroups)) for consistency. Allow for symbol
arrays to index data frame columns in the correct order.
 
# Arguments
- `sf_vec` : Flattened scale factor vector. Should be the same order as the underlying data generated by `generate_scale_factor_names`
- `n_taxa` : Number of functional groups or taxanomy classes.
- `n_biogroups` : Number of biogroups sharing scaling factors.
- `n_p_types` : Number of parameters using scale coefficients
 
# Returns
- reshape(sf_vec, (n_taxa, n_p_types, n_biogroups))
"""
function scale_factor_vec_to_array(
    sf_vec::AbstractVector{T}, n_taxa::Int64, n_biogroups::Int64, n_p_types::Int64
)::Array{T,3} where T<:Union{Float64,String,Tuple}
    return reshape(sf_vec, (n_taxa, n_p_types, n_biogroups))
end
 
"""
    scale_factor_array_to_vec(sf_vec::Array{T, 3})::Vector{T} where T <: Union{Float64, String, Tuple}
 
Reshape a scale factor array of dimensions [taxa ⋅ param_type ⋅ biogroups] to a flatenned
vector. The implementastion is a simple wrapper of vec(arr) for consistency. Allow for
string arrays to index data frame columns in the correct order.
 
# Arguments
- `sf_arr` : Scale factor array. Should be the same order as the underlying data generated by `generate_scale_factor_names`
 
# Returns
- vec(sf_arr)
"""
function scale_factor_array_to_vec(
    sf_arr::Array{T,3}
)::Vector{T} where T<:Union{Float64,String,Tuple}
    return vec(sf_arr)
end
 
"""
    generate_scale_factor_names(bioregion_ids::Vector{Int64})::Array{String, 3}
 
Given a list of bioregion generate the names of the columns corresponding to bioregions.
 
The format should be biogroup_<id>_<param_name>_<taxa_name>
"""
function generate_scale_factor_names(bioregion_ids::Vector{Int64})::Array{String,3}
    fg_names::Vector{Symbol} = ADRIA.functional_group_names()
    param_names::Tuple{Symbol,Symbol} = (:linear_extension, :mb_rate)
 
    n_biogroups::Int64 = length(bioregion_ids)
    n_taxa::Int64 = length(fg_names)
    n_type_factors::Int64 = 2
 
    factor_names::Array{String,3} = Array{String,3}(
        undef, n_taxa, n_type_factors, n_biogroups
    )
 
    for (bg_idx, bg) in enumerate(bioregion_ids),
        (pn_idx, pn) in enumerate(param_names),
        (fg_idx, fg) in enumerate(fg_names)
 
        factor_names[fg_idx, pn_idx, bg_idx] = "$(pn)_scale_cb_group_$(bg)_$(fg)"
    end
 
    return factor_names
end
 
"""
    accel_params_array_to_vec(accel_params::AbstractArray{T, 2})::Vector{T} where T <: Union{Float64, String, Tuple}
"""
function accel_params_array_to_vec(
    accel_params::AbstractArray{T,2}
)::Vector{T} where T<:Union{Float64,String,Tuple}
    return vec(accel_params)
end
 
"""
    accel_params_vec_to_array(accel_params::AbstractVector{T}, n_biogroups::Int64)::Array{T, 2} where T <: Union{Float64, String, Tuple}
"""
function accel_params_vec_to_array(
    accel_params::AbstractVector{T},
    n_biogroups::Int64
)::Array{T,2} where T<:Union{Float64,String,Tuple}
    return reshape(accel_params, (n_biogroups, 3))
end
 
"""
    generate_growth_accel_names(biogroup_ids::Vector{Int64})::Array{String, 2}
 
The format should be growth_accel_<param_name>_<biogroup_id>. Return an array of dimensions
[biogroups ⋅ params]
"""
function generate_growth_accel_names(biogroup_ids::Vector{Int64})::Array{String,2}
    param_names::Tuple{Symbol,Symbol,Symbol} = (:steepness, :height, :midpoint)
 
    n_params::Int64 = 3
    n_biogroups::Int64 = length(biogroup_ids)
 
    factor_names::Matrix{String} = Matrix{String}(undef, n_biogroups, n_params)
    for (pn_idx, pn) in enumerate(param_names),
        (bg_idx, bg) in enumerate(biogroup_ids)
 
        factor_names[bg_idx, pn_idx] = "growth_acceleration_cb_group_$(bg)_$(pn)"
    end
    return factor_names
end


"""
    target_param_names()
"""
function target_param_names()
    return [
        "linear_extension", "mb_rate", "dist_mean"
    ]
end

"""
    sc_fg_param_idxs(param_name::String, coral_df::DataFrame):mean_colony_diameter_m:Vector{Int64}

Return the indices of the parameter such that it returns them in the ordered used in ADRIA.

Makes it easier to insert bounds into vector of sample bounds from a ordered source file.

# Example

```julia
julia> ordered_idxs = sc_fg_param_idxs(param_name, coral_df)

julia> coral_df[ordered_idxs, :].fieldname
35-element Vector{Symbol}:
 :tabular_Acropora_1_1_linear_extension
 :tabular_Acropora_1_2_linear_extension
 :tabular_Acropora_1_3_linear_extension
...
 :corymbose_Acropora_2_1_linear_extension
...
 :corymbose_non_Acropora_3_1_linear_extension
...
 :small_massives_4_1_linear_extension
...
 :large_massives_5_1_linear_extension
...
```

"""
function sc_fg_param_idxs(param_name::String, coral_df::DataFrame)::Vector{Int64}
    idxs = zeros(Int64, 35)

    n_taxa, n_sizes = size(ADRIA.bin_widths())
    counter::Int64 = 1
    for grp in 1:n_taxa, sc in 1:n_sizes
        idxs[counter] = extract_param_group_idx(coral_df, "$(grp)_$(sc)_$(param_name)")[1]
        counter += 1
    end
    return idxs
end

"""
    set_bounds!(sample_bounds, coral_param_idxs, lower_bounds::Vector{Float64}, upper_bounds::Vector{Float64})::Nothing
"""
function set_bounds!(
    sample_bounds,
    coral_param_idxs,
    lower_bounds::Vector{Float64},
    upper_bounds::Vector{Float64}
)::Nothing
    if any(lower_bounds .> upper_bounds)
        msg = "At least one lower bound given is less then the corresponding upper bound"
        throw(ArgumentError(msg))
    end
    sample_bounds[coral_param_idxs] .= collect(zip(lower_bounds, upper_bounds))
    return nothing
end

function flatten_group_size(param_matrix::Matrix{Float64})::Vector{Float64}
    n_taxa, n_sizes = size(param_matrix)
    return reshape(permutedims(param_matrix, (2, 1)), (n_taxa * n_sizes,))
end

ecorrap_params = open_dataset(ECORRAP_PARAM_PATH)

# Construct linear extension parameter bounds
linear_extension_mean = copy(ecorrap_params.filled_lin_ext_mean)
linear_extension_mean[:, 7] .= 0.0

lin_ext_lb = linear_extension_mean.data[:, :] .* 0.9
lin_ext_ub = linear_extension_mean.data[:, :] .* 1.1

lin_ext_lb = flatten_group_size(lin_ext_lb)
lin_ext_ub = flatten_group_size(lin_ext_ub)

# Construct background mortality parameter bounds
mb_rate_mean = ecorrap_params.filled_mb_rate_mean

mb_rate_lb = mb_rate_mean.data[:, :] .* 0.9
mb_rate_ub = mb_rate_mean.data[:, :] .* 1.1

mb_rate_lb = flatten_group_size(mb_rate_lb)
mb_rate_ub = flatten_group_size(mb_rate_ub)

# Define parameter space to scan over
coral_params = ADRIA.component_params(ADRIA.model_spec(dom), ADRIA.Coral)

# Extract just the target coral parameters
lin_ext_idx, mbrate_idx, dhw_tol_mean_idx =
    extract_param_group_idx.([coral_params], target_param_names())

coral_param_idx = vcat(
    lin_ext_idx, mbrate_idx, dhw_tol_mean_idx
)
coral_params = coral_params[sort(coral_param_idx), :]
coral_param_names = coral_params.fieldname

# Get updated parameter positions
lin_ext_idx, mbrate_idx, dhw_tol_mean_idx =
    extract_param_group_idx.([coral_params], target_param_names())

lin_ext_idx = sc_fg_param_idxs("linear_extension", coral_params)
mbrate_idx = sc_fg_param_idxs("mb_rate", coral_params)

sample_bounds = collect(zip(
    coral_params.lower_bound,
    coral_params.upper_bound
))

# Adjust bounds for initial mean DHW tolerance
sample_bounds[dhw_tol_mean_idx] .= collect(zip(coral_params[dhw_tol_mean_idx, :lower_bound], coral_params[dhw_tol_mean_idx, :val]))

# Set bounds for linear extension and mb rate from ecorrap data
set_bounds!(sample_bounds, lin_ext_idx, lin_ext_lb, lin_ext_ub)
set_bounds!(sample_bounds, mbrate_idx, mb_rate_lb, mb_rate_ub)

coral_start_idx = 1
coral_end_idx = length(sample_bounds)

# If it becomes official, this group should be added to the canonical_reefs to avoid this ugliness
manually_added_group = 28
const BIOGROUPS_ORDERING = sort(union(unique(canonical_gpkg.CB_CALIB_GROUPS), manually_added_group))

# Number of unique biogroups used in calibration
n_biogroups = length(BIOGROUPS_ORDERING)

# Add parameters for location-specific scaling
n_groups = 5
n_size_classes = 7
n_factors = 2  # growth, mortality

# append bounds to sample bounds
loc_coef_start_idx = coral_end_idx + 1

biogroup_scale_factors::Array = Array{Tuple{Float64,Float64}}(
    undef, n_groups, n_factors, n_biogroups
)
biogroup_scale_factors[:, 1, :] .= Ref((0.7, 1.5))
biogroup_scale_factors[:, 2, :] .= Ref((-1.0, 1.0))
append!(sample_bounds, scale_factor_array_to_vec(biogroup_scale_factors))
loc_coef_end_idx = length(sample_bounds)

# Location-based growth scaling

# Parameter indexs
STEEPNESS_PARAM_IDX = 1
HEIGHT_PARAM_IDX = 2
MIDPOINT_PARAM_IDX = 3

growth_acc_start_idx = loc_coef_end_idx + 1

biogroup_accel_bounds::Matrix = Matrix{Tuple{Float64,Float64}}(undef, n_biogroups, 3)

biogroup_accel_bounds[:, STEEPNESS_PARAM_IDX] .= [(-20.0, -15.0)]
biogroup_accel_bounds[:, HEIGHT_PARAM_IDX] .= [(0.0, 2.0)]
biogroup_accel_bounds[:, MIDPOINT_PARAM_IDX] .= [(0.0, 0.3)]

append!(sample_bounds, accel_params_array_to_vec(biogroup_accel_bounds))
growth_acc_end_idx = length(sample_bounds)

sc_dist_bounds = fill((0.25, 2.0), n_biogroups)

sc_dist_start_idx = growth_acc_end_idx + 1
append!(sample_bounds, sc_dist_bounds)
sc_dist_end_idx = length(sample_bounds)

global PARAM_IDXS = [
    coral_start_idx, coral_end_idx,
    loc_coef_start_idx, loc_coef_end_idx,
    growth_acc_start_idx, growth_acc_end_idx,
    sc_dist_start_idx, sc_dist_end_idx
]

global CORAL_PARAM_NAMES = coral_params.fieldname
global SCALE_FACTOR_NAMES = scale_factor_array_to_vec(
    generate_scale_factor_names(collect(1:length(BIOGROUPS_ORDERING)))
)
global GROWTH_ACCEL_NAMES = accel_params_array_to_vec(
    generate_growth_accel_names(collect(1:length(BIOGROUPS_ORDERING)))
)

# Utility functions for domain and parameter calibration setup

"""
Reshape the growth acceleration parameters from a vector a matrix of shape [n_parameters ⋅ n_locs]
"""
function reshape_growth_accel_parameters(
    params::Vector{Float64};
    n_locs=length(TARGET_DOM_IDXS)
)::Matrix{Float64}
    return reshape(params, (3, n_locs))
end

"""
    insert_init_loc_cover!(dom, lambdas; raw_ltmp_reef_data=raw_ltmp_reef_data, rm_ltmp_taxa=rm_ltmp_taxa, target_dom_idxs=TARGET_DOM_IDXS )::Nothing

Recalculate initial cover of target locations to match photogrammetry coral composition and
manta tow total cover. Use the given lambda calculation
"""
function insert_init_loc_cover!(
    dom,
    lambdas;
    observations::LocationDataStore=COMBINED_STORE,
    biogroup_ord::Vector{Int64}=BIOGROUPS_ORDERING,
)::Nothing
    # Change the coral composition of location for which we have data
    for (idx, dom_idx) in enumerate(observations.composition_to_domain)
        # Maintain the original cover levels but change the composition
        tmp_cover::Float64 = sum(dom.init_coral_cover[:, dom_idx])
        non_missing_idx::Int64 = findfirst(
            x -> !ismissing(x), observations.coral_composition[:, 1, idx]
        )
        size_class_props = size_class_distribution(
            lambdas[findfirst(biogroup_ord .== dom.loc_data.CB_CALIB_GROUPS[dom_idx])],
            ADRIA.bin_edges()[1, :]
        )
        loc_cov = observations.coral_composition[
            non_missing_idx, :, idx
        ] .* size_class_props' ./ sum(observations.coral_composition[non_missing_idx, :, idx])
        dom.init_coral_cover[:, dom_idx] .=
            reshape(permutedims(loc_cov, (2, 1)), (35,)) .* tmp_cover
    end
    for (idx, dom_idx) in enumerate(observations.ltmp_cover_to_domain)
        tot_cov =
            observations.ltmp_coral_cover[
                idx, findfirst(x -> !ismissing(x), observations.ltmp_coral_cover[idx, :])
            ] ./ dom.loc_data.k[dom_idx]
        dom.init_coral_cover[:, dom_idx] .*= tot_cov ./ sum(dom.init_coral_cover[:, dom_idx])
    end

    return nothing
end

function get_scale_factors(
    scenario_df::DataFrame;
    scale_factor_names::Vector{String}=SCALE_FACTOR_NAMES
)::Array{Float64,3}
    return scale_factor_vec_to_array(
        collect(scenario_df[1, scale_factor_names]), 5, length(BIOGROUPS_ORDERING), 2
    )
end

function copy(dom::ReefModDomain)::ReefModDomain
    return ReefModDomain(
        dom.name,
        dom.RCP,
        dom.env_layer_md,
        dom.scenario_invoke_time,
        dom.conn,
        dom.loc_data,
        dom.loc_id_col,
        dom.cluster_id_col,
        dom.init_coral_cover,
        dom.coral_growth,
        dom.loc_ids,
        dom.dhw_scens,
        dom.wave_scens,
        dom.cyclone_mortality_scens,
        dom.model,
        dom.sim_constants
    )
end

"""
    setup_run(dom::Domain, sampled_params::Vector{Float64}; param_names::Vector{Symbol}=CORAL_PARAM_NAMES, param_idxs=PARAM_IDXS, loc_idxs=target_dom_idxs )::Nothing

Insert coral parameters into dataframe, reconstruct size class distribution of target
locations and extract scale factors and growth acceleration parameters.
"""
function setup_run(
    dom::Domain,
    sampled_params::Vector{Float64};
    param_names::Vector{Symbol}=CORAL_PARAM_NAMES,
    scale_factor_names::Vector{String}=SCALE_FACTOR_NAMES,
    growth_accel_names::Vector{String}=GROWTH_ACCEL_NAMES,
    param_idxs=PARAM_IDXS,
)::Tuple{Domain,DataFrame}
    # The only changes between domain objects is initial coral cover
    new_dom = copy(dom)
    new_dom.init_coral_cover = copy(dom.init_coral_cover)

    scen = ADRIA.param_table(new_dom)
    coral_param_values = sampled_params[param_idxs[1]:param_idxs[2]]
    scen[!, param_names] .= coral_param_values'
    scen[!, scale_factor_names] .= sampled_params[param_idxs[3]:param_idxs[4]]'
    scen[!, growth_accel_names] .= sampled_params[param_idxs[5]:param_idxs[6]]'

    insert_init_loc_cover!(
        new_dom,
        sampled_params[param_idxs[7]:param_idxs[8]]
    )

    return new_dom, scen
end
